### ISSUE TITLE
describe.only is not being detected

### ISSUE THREAD

**Issue by googol7** [molindo/eslint-config-molindo#85]
Currently this is being used: https://github.com/molindo/eslint-config-molindo/blob/master/cypress.js

This could be used: https://www.npmjs.com/package/eslint-plugin-no-only-tests

**Comment by amannn** [comment]
True, good point!

This should be fixed with https://github.com/molindo/eslint-config-molindo/pull/84. You can try the prerelease `eslint-config-molindo@6.0.0-alpha.6` if you like, a stable release should be ready soon.

Please note that [ESLint 8 is required now](https://github.com/molindo/eslint-config-molindo/pull/84/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed).
